version: '3.7'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5002:5000
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://ttest:ttest@db:5432/ttest
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ttest
      - POSTGRES_PASSWORD=ttest
      - POSTGRES_DB=ttest
    ports:
      - 5435:5432

volumes:
  postgres_data:
