"""add mimetype

Revision ID: cb63b7fc4d13
Revises: 08a3ff6e377a
Create Date: 2020-04-04 12:39:16.987878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb63b7fc4d13'
down_revision = '08a3ff6e377a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('mimetype', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'mimetype')
    # ### end Alembic commands ###
