"""delete book table

Revision ID: 3e445cb7ad04
Revises: ce473df5b2ad
Create Date: 2020-03-20 17:51:41.141660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e445cb7ad04'
down_revision = 'ce473df5b2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.add_column('file', sa.Column('file_type', postgresql.ENUM('pdf', 'doc', 'xls', name='file_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_type')
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('also', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    # ### end Alembic commands ###
