"""document

Revision ID: 447dc42d8413
Revises: bfe4ad8cfa6e
Create Date: 2020-03-19 20:48:21.235998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '447dc42d8413'
down_revision = 'bfe4ad8cfa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', postgresql.ENUM("article", "court", "book", "magazine", "link", "other", name='document_type'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.execute('drop type document_type;')
    # ### end Alembic commands ###
