"""user

Revision ID: 731253129be2
Revises: a95dfd108bf1
Create Date: 2020-03-18 20:46:28.497741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731253129be2'
down_revision = 'a95dfd108bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
