"""also

Revision ID: a95dfd108bf1
Revises: d356a5b5892d
Create Date: 2020-03-18 20:24:27.337702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95dfd108bf1'
down_revision = 'd356a5b5892d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('also', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'also')
    # ### end Alembic commands ###
