"""file

Revision ID: ce473df5b2ad
Revises: 447dc42d8413
Create Date: 2020-03-19 23:29:16.567516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce473df5b2ad'
down_revision = '447dc42d8413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('description', sa.String(), nullable=True))
    op.add_column('document', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_file_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'file_id')
    op.drop_column('document', 'description')
    op.drop_table('file')
    # ### end Alembic commands ###
